### ISSUE TITLE
Clustering Traces

### ISSUE THREAD

**Issue by insodus9** [mengyingzhou/FlexHTTP#1]
Hi,

in order to create labels for the training of the supervised learning model, in section 3.3.2. you describe that you obtain labels by clustering the traces. As far as I understand, in this way you treat similar traces as if they were equal. I like this approach and I would like to adapt it but unfortunately I can't find the corresponding code.

Could you maybe tell me 
1) how many clusters you have used, i.e. how large the k parameter was. 
2) did you use the default k-means clustering from sklearn? 

Thank you

**Comment by mengyingzhou** [comment]
Hi,

Thanks for liking FlexHTTP. 
To answer your questions,
1. We set K equal to 240.
2. Yes. But we didn't cover this part of the code in this repo. In this prototype, we just set each URL as a cluster.

Thanks
Mengying
